kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/akhenakh/insidetree

steps:
- name: test
  image: golang
  commands:
  - go get
  - go get github.com/stretchr/testify/require
  - go test
